version: '3.7'
services:
    frontend: 
      build: 
        context: .
        dockerfile: frontend.Dockerfile
      environment:
        REACT_APP_API_BASE_URL:
      ports:
        - 3000:3000
      depends_on:
        - "backend"
      volumes: 
        - ${PWD}/frontend:/frontend
        # use the node_modules from inside the container and not from local machine
        - /frontend/node_modules
      command: npm run start
  
    backend: 
      build: 
        context: .
        dockerfile: backend.Dockerfile
      environment: 
        ENV: 
      ports:
        - 3001:3001
      volumes: 
        - ${PWD}/backend:/backend
        # pseudo database 
        - ${PWD}/database:/database
        # use the node_modules from inside the container and not from local machine
        - /backend/node_modules
      command: npm run start

    api-tests:
      build: 
        context: .
        dockerfile: api-tests.Dockerfile
      environment: 
        API_BASE_URL: 'http://backend:3001'
      volumes:
        - ${PWD}/api-tests:/api-tests
        # use the node_modules from inside the container and not from local machine
        - /api-tests/node_modules
      depends_on:
          - backend

    ui-tests:
      build: 
        context: .
        dockerfile: ui-tests.Dockerfile
      environment:
        CYPRESS_baseUrl: 'http://frontend:3000'
      volumes:
        - ${PWD}/ui-tests:/ui-tests
        # include the test framework shared library 
        - ${PWD}/database:/database
        - ${PWD}/test-framework-lib:/test-framework-lib
        # use the node_modules from inside the container and not from local machine
        - /ui-tests/node_modules
      depends_on:
          - frontend
          - backend
    
    

    
